$wall = /home/artturi/Pictures/Wallpapers/onepiecewall.jpg
$text_color = rgba(216, 222, 233, 0.80)
$main_monitor = DP-3

# BACKGROUND (Both monitors)
background {
    monitor =
    path = $wall
    blur_passes = 2
    contrast = 0.89
    brightness = 0.81
}

# GENERAL
general {
    no_fade_in = true 
    grace = 0
    disable_loading_bar = true
}

# MAIN DECORATIVE BOX (Main Monitor)
shape {
    monitor = $main_monitor
    size = 400, 400
    color = rgba(35, 34, 51, 0.62)
    rounding = 30
    position = 0, -70
    halign = center
    valign = center
}

# NAME
label {
    monitor = $main_monitor
    text = Welcome $USER :)
    color = rgba(216, 222, 233, 0.80)
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 20
    font_family = SF Pro Display Bold
    position = 0, 80
    halign = center
    valign = center
}

# Time
label {
    monitor = $main_monitor
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = $text_color
    font_size = 60
    position = 0, -10
    halign = center
    valign = center
}

# Day/Date
label {
    monitor = $main_monitor
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = $text_color
    font_size = 19
    position = 0, -80
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor = $main_monitor
    size = 320, 55
    outline_thickness = 0
    dots_center = true
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    placeholder_text = <i><span>   Enter Pass</span></i>
    position = 0, -180
    halign = center
    valign = center
}

