##############################
##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}


# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#     name = no-gaps-wtv1
#     match:float = false
#     match:workspace = w[tv1]
#
#     border_size = 0
#     rounding = 0
# }
#
# windowrule {
#     name = no-gaps-f1
#     match:float = false
#     match:workspace = f[1]
#
#     border_size = 0
#     rounding = 0
# }

workspace = 1, monitor:DP-3
workspace = 2, monitor:DP-3
workspace = 3, monitor:DP-3
workspace = 4, monitor:DP-3
workspace = 5, monitor:DP-3
workspace = 6, monitor:HDMI-A-1
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1

# Transparency
windowrule {
    name = terminal
    match:class = ^(kitty)$
    opacity = 0.85
}

windowrule {
    name = allow-tearing-cs2
    match:class = ^(cs2)$
    immediate = on
}

windowrule {
    name = allow-tearing-cs2-exe
    match:class = ^(cs2\.exe)$
    immediate = on
}

windowrule {
    name = Spotify
    match:class = ^(spotify)$
    workspace = 6
}

windowrule {
    name = Discord
    match:class = ^(vesktop)$
    workspace = 10
}

windowrule {
    name = Telegram
    match:initial_class = ^(org.telegram.desktop)$
    workspace = 10
}

windowrule {
    name = Code-OSS
    match:class = ^(code)$
    workspace = 5
    opacity = 0.85
}

windowrule {
    name = Qalculate
    match:class = ^(qalculate-gtk)$
    
    float = yes
    center = yes
    size = 700 500
    opacity = 0.85
    border_size = 4px
}

windowrule {
    name = Lazydocker
    match:class = ^(floating_docker)$

    float = yes
    center = yes
    size = 1100 750
    opacity = 0.85
    border_size = 4px
}

layerrule = match:namespace swaync-control-center, blur on
layerrule = match:namespace swaync-control-center, ignore_alpha 0.5

layerrule = match:namespace swaync-notification-window, blur on
layerrule = match:namespace swaync-notification-window, ignore_alpha 0.5
